[project]
name = "pybattery"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pyyaml",
    "pydantic",
    "minimalmodbus",
    "pyserial",
    "pyrover @ git+https://github.com/sebmartin/pyrover.git",
]

[dependency-groups]
dev = ["pytest", "ruff", "pytest-cov"]
rpi = ["RPLCD", "RPi.GPIO", "adafruit-circuitpython-dht"]

[project.scripts]
pybattery = "pybattery.main:main"

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["pybattery*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
